name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: microsoft/playwright-github-action@v1

      - run: npm install

      - run: npm test

      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/test
